/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package y.proyectofinal;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        lbladministrador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bttañadirusuari = new javax.swing.JButton();
        lblmenu = new javax.swing.JLabel();
        bttnuevasmarcas = new javax.swing.JButton();
        bttnuevomodelo = new javax.swing.JButton();
        bttcerrarsesion = new javax.swing.JButton();
        bttkardex = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbladministrador.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        lbladministrador.setForeground(new java.awt.Color(204, 204, 0));
        lbladministrador.setText("SEGMENTO DE ADMInISTRADOR");
        getContentPane().add(lbladministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 640, 50));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 30, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 30, 20));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        bttañadirusuari.setBackground(new java.awt.Color(204, 204, 0));
        bttañadirusuari.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        bttañadirusuari.setText("AÑADIR NUEVO USUARIO");
        bttañadirusuari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttañadirusuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttañadirusuariActionPerformed(evt);
            }
        });

        lblmenu.setBackground(new java.awt.Color(204, 204, 0));
        lblmenu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        lblmenu.setForeground(new java.awt.Color(204, 204, 0));
        lblmenu.setText("MENU PRINCIPAL");

        bttnuevasmarcas.setBackground(new java.awt.Color(204, 204, 0));
        bttnuevasmarcas.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        bttnuevasmarcas.setText("AGREGAR NUEVo Modelo");
        bttnuevasmarcas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnuevasmarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnuevasmarcasActionPerformed(evt);
            }
        });

        bttnuevomodelo.setBackground(new java.awt.Color(204, 204, 0));
        bttnuevomodelo.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        bttnuevomodelo.setText("Agregar NUEVO marca");
        bttnuevomodelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnuevomodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnuevomodeloActionPerformed(evt);
            }
        });

        bttcerrarsesion.setBackground(new java.awt.Color(204, 204, 0));
        bttcerrarsesion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        bttcerrarsesion.setText("Cerrar Sesion ");
        bttcerrarsesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttcerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcerrarsesionActionPerformed(evt);
            }
        });

        bttkardex.setBackground(new java.awt.Color(204, 204, 0));
        bttkardex.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        bttkardex.setText("KARDEX ENTRADA");
        bttkardex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttkardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttkardexActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 3, 18)); // NOI18N
        jButton1.setText("KARDEX SALIDA");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttcerrarsesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnuevasmarcas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnuevomodelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttañadirusuari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttkardex, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblmenu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmenu)
                .addGap(18, 18, 18)
                .addComponent(bttkardex)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(bttañadirusuari)
                .addGap(18, 18, 18)
                .addComponent(bttnuevasmarcas)
                .addGap(18, 18, 18)
                .addComponent(bttnuevomodelo)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(bttcerrarsesion)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 580));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("CENTRO DE INVENTARIOS DE CELULARES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 400, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FONDO SAGA2.png"))); // NOI18N
        jLabel1.setText("AGREGAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttcerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcerrarsesionActionPerformed

        int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres cerrar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (opcion == JOptionPane.YES_OPTION) {
            Inicio in = new Inicio();
            in.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_bttcerrarsesionActionPerformed

    private void bttnuevomodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnuevomodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnuevomodeloActionPerformed

    private void bttañadirusuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttañadirusuariActionPerformed
        // TODO add your handling code here:
        CrearUsuario us = new CrearUsuario();
        us.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_bttañadirusuariActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void bttkardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttkardexActionPerformed
        Krex kr = new Krex();
        kr.setVisible(rootPaneCheckingEnabled);
        this.dispose();


    }//GEN-LAST:event_bttkardexActionPerformed

    private void bttnuevasmarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnuevasmarcasActionPerformed
        AgregarNuevasMarcas agr = new AgregarNuevasMarcas();
        agr.setVisible(rootPaneCheckingEnabled);
        agr.mostrarDatosMarcas();
        this.dispose();


    }//GEN-LAST:event_bttnuevasmarcasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Stock s=new Stock();
        s.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttañadirusuari;
    private javax.swing.JButton bttcerrarsesion;
    private javax.swing.JButton bttkardex;
    private javax.swing.JButton bttnuevasmarcas;
    private javax.swing.JButton bttnuevomodelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbladministrador;
    private javax.swing.JLabel lblmenu;
    // End of variables declaration//GEN-END:variables
}
