/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package y.proyectofinal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static y.proyectofinal.Krex.fechaActual;

/**
 *
 * @author User
 */
public class Agregar_Marca extends javax.swing.JFrame {

    Conexionn cn = new Conexionn();
    Connection con = cn.conectar();

    /**
     * Creates new form Agregar_Marca
     */
    public Agregar_Marca() {
        initComponents();
        this.proveedor();
        lbl_fecha.setText(fechaActual());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public static String fechaActual() {
        LocalDate fecha = LocalDate.now();
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return fecha.format(formatoFecha);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nombremarca = new javax.swing.JTextField();
        cbx_proveedor = new javax.swing.JComboBox<>();
        txt_comentarios = new javax.swing.JTextField();
        lbl_fecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_marca = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("AGREGAR NUEVA MARCA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("NOMBRE DE LA MARCA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("FECHA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("COMENTARIOS:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("PROVEDOR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        txt_nombremarca.setBackground(new java.awt.Color(0, 51, 102));
        txt_nombremarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombremarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombremarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 220, -1));

        cbx_proveedor.setBackground(new java.awt.Color(0, 51, 102));
        cbx_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_proveedorActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 220, -1));

        txt_comentarios.setBackground(new java.awt.Color(0, 51, 102));
        txt_comentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_comentariosActionPerformed(evt);
            }
        });
        getContentPane().add(txt_comentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 270, 40));

        lbl_fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha.setText("DD/MM/YYYY");
        getContentPane().add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 130, 40));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 590, 110, 40));

        tb_marca.setBackground(new java.awt.Color(255, 255, 153));
        tb_marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID INGRESO DE MARCA ", "NOMBRE MARCA", "PROVEEDOR", "COMENTARIOS", "FECHA"
            }
        ));
        jScrollPane2.setViewportView(tb_marca);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 790, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 110, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\SOLOFONDOOOOO.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 920, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombremarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombremarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombremarcaActionPerformed

    private void txt_comentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_comentariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_comentariosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Administrador a = new Administrador();
        a.setVisible(rootPaneCheckingEnabled);
        
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        try {
            // Obtén el nuevo ID válido para el vehículo desde la base de datos

            int idmarca = obtenerNuevoIdMarcasFromDatabase();
            PreparedStatement ps = con.prepareStatement("INSERT INTO `marcas` (idmarca, Mar_nombre,Proveedor, Comentarios, fecha ) VALUES (?, ?, ?, ?, ?)");

            ps.setInt(1, idmarca);
            ps.setString(2, txt_nombremarca.getText());
            ps.setString(3, cbx_proveedor.getSelectedItem().toString());
            ps.setString(4, txt_comentarios.getText());
            ps.setString(5, lbl_fecha.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos registrados");

        } catch (SQLException e) {
            System.out.println("Error: " + e);

        }
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM marcas");

            // Limpiar la tabla muesrta antes de agregar nuevos datos
            DefaultTableModel model = (DefaultTableModel) tb_marca.getModel();
            model.setRowCount(0);

            // Recorrer el resultado y agregar los datos a la tabla muesrta
            while (rs.next()) {
                int id_marca = rs.getInt("idmarca");
                String Mar_nombre = rs.getString("Mar_nombre");
                String Proveedor = rs.getString("Proveedor");
                String Comentarios = rs.getString("Comentarios");
                String fecha = rs.getString("fecha");

                // Agregar los datos a la tabla muesrta
                model.addRow(new Object[]{id_marca, Mar_nombre, Proveedor, Comentarios, fecha});
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener los datos de la tabla: " + e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbx_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_proveedorActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cbx_proveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Marca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Marca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JTable tb_marca;
    private javax.swing.JTextField txt_comentarios;
    private javax.swing.JTextField txt_nombremarca;
    // End of variables declaration//GEN-END:variables

    private int obtenerNuevoIdMarcasFromDatabase() {
        int nuevoId = 0;

        try {
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT MAX(id_marca) FROM marcas");

            if (resultSet.next()) {
                int maxId = resultSet.getInt(1);
                nuevoId = maxId + 1;
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el nuevo ID: " + e);
        }

        return nuevoId;

    }

    private void proveedor() {
        Connection cn = Conexionn.conectar();
        String sql = "select * from catalogo_kardex";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbx_proveedor.removeAllItems();
            cbx_proveedor.addItem("Seleccione PROVEEDOR");
            while (rs.next()) {
                cbx_proveedor.addItem(rs.getString("proveedor"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias");
        }

    }
}
