/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package y.proyectofinal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static y.proyectofinal.AgregarNuevasMarcas.fechaActual;

/**
 *
 * @author User
 */
public class Krex extends javax.swing.JFrame {

    Conexionn cn = new Conexionn();
    Connection con = cn.conectar();

    public Krex() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_fecha.setText(fechaActual());
        this.CargarComboCategorias();
        this.proveedor();
        this.modelo();
        this.almacenamiento();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kardex = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbx_marca = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbx_proveedor = new javax.swing.JComboBox<>();
        cbx_modelo = new javax.swing.JComboBox<>();
        cbx_almacenamiento = new javax.swing.JComboBox<>();
        lbl_fecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_valorunitario = new javax.swing.JTextField();
        btt_guardar = new javax.swing.JButton();
        txt_detalles = new javax.swing.JTextField();
        lbl_valortotalentrada = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_cantidadexistencia = new javax.swing.JLabel();
        lbl_valorunitexistencia = new javax.swing.JLabel();
        lbl_totalexistecia = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("KARDEX");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 0, 194, 41));

        tb_kardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_Kardex", "FECHA", "DETALLES", "CANTIDAD", "VALOR UNITARIO", "VALOR TOTAL", "CANTIDAD", "VALOR UNITARIO", "VALOR TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tb_kardex);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1110, 328));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("MARCA:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 20));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Fecha:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        cbx_marca.setBackground(new java.awt.Color(0, 51, 102));
        cbx_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_marca.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cbx_marca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbx_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 240, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("PROVEEDOR:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, -1));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("MODELO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 80, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("EXISTENCIAS");
        jPanel3.add(jLabel4);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 370, 30));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("ALMACENAMIENTO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setBackground(new java.awt.Color(102, 204, 0));
        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("  ENTRADAS");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 370, 30));

        cbx_proveedor.setBackground(new java.awt.Color(0, 51, 102));
        cbx_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_proveedor.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cbx_proveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbx_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 240, -1));

        cbx_modelo.setBackground(new java.awt.Color(0, 51, 102));
        cbx_modelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_modelo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cbx_modelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbx_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_modeloActionPerformed(evt);
            }
        });
        getContentPane().add(cbx_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 240, -1));

        cbx_almacenamiento.setBackground(new java.awt.Color(0, 51, 102));
        cbx_almacenamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_almacenamiento.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        cbx_almacenamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbx_almacenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 240, -1));

        lbl_fecha.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fecha.setText("DD/MM/YY");
        getContentPane().add(lbl_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("CANTIDAD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, -1));

        txt_cantidad.setBackground(new java.awt.Color(0, 51, 102));
        txt_cantidad.setForeground(new java.awt.Color(255, 255, 255));
        txt_cantidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 130, -1));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("VALOR UNITARIO:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        txt_valorunitario.setBackground(new java.awt.Color(0, 51, 102));
        txt_valorunitario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_valorunitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 130, -1));

        btt_guardar.setBackground(new java.awt.Color(204, 204, 0));
        btt_guardar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        btt_guardar.setText("GUARDAR");
        btt_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(btt_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 205, 110, 30));

        txt_detalles.setBackground(new java.awt.Color(0, 51, 102));
        txt_detalles.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txt_detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 190, 60));

        lbl_valortotalentrada.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_valortotalentrada.setForeground(new java.awt.Color(255, 255, 255));
        lbl_valortotalentrada.setText("$00,00");
        getContentPane().add(lbl_valortotalentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 60, 20));

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 0));
        jLabel14.setText("DETALLES:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 0));
        jLabel17.setText("CANTIDAD:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 0));
        jLabel18.setText("VALOR UNITARIO:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        jLabel19.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 0));
        jLabel19.setText("VALOR TOTAL:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 0));
        jLabel15.setText("valor Total:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        lbl_cantidadexistencia.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_cantidadexistencia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cantidadexistencia.setText("$00,00");
        getContentPane().add(lbl_cantidadexistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 80, 20));

        lbl_valorunitexistencia.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_valorunitexistencia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_valorunitexistencia.setText("$00,00");
        getContentPane().add(lbl_valorunitexistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 70, 20));

        lbl_totalexistecia.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        lbl_totalexistecia.setForeground(new java.awt.Color(255, 255, 255));
        lbl_totalexistecia.setText("$00,00");
        getContentPane().add(lbl_totalexistecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 70, 20));

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jButton2.setText("CALCULAR existencia");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 220, 30));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel11.setBackground(new java.awt.Color(0, 0, 102));
        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 0));
        jLabel11.setText("ENTRADAS");
        jPanel2.add(jLabel11);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 310, 20));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("EXISTENCIA");
        jPanel5.add(jLabel12);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 350, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\SOLOFONDOOOOO.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 640));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));

        jLabel16.setBackground(new java.awt.Color(0, 0, 102));
        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 0));
        jLabel16.setText("ENTRADAS");
        jPanel4.add(jLabel16);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 370, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static String fechaActual() {
        LocalDate fecha = LocalDate.now();
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return fecha.format(formatoFecha);
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio i = new Inicio();
        i.setVisible(rootPaneCheckingEnabled);
        this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbx_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_modeloActionPerformed

    private void btt_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_guardarActionPerformed
        try {
            // Obtén el nuevo ID válido para el vehículo desde la base de datos

            int id_kardex = obtenerNuevoIdVehiculoFromDatabase();
            PreparedStatement ps = con.prepareStatement("INSERT INTO `kardex` (id_kardex, marca, proveedor, modelo, almacenamiento, cantidad, "
                        + "valor_unitario, total_entrada, fecha, cantidad_existencia, valorunit_existencia, valortotal_existencia, detalles) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?)");

            ps.setInt(1, id_kardex);
            ps.setString(2, cbx_marca.getSelectedItem().toString());
            ps.setString(3, cbx_proveedor.getSelectedItem().toString());
            ps.setString(4, cbx_modelo.getSelectedItem().toString());
            ps.setString(5, cbx_almacenamiento.getSelectedItem().toString());
            ps.setString(6, txt_cantidad.getText());
            ps.setString(7, txt_valorunitario.getText());
            ps.setString(8, lbl_valortotalentrada.getText());
            ps.setString(9, lbl_fecha.getText());
            ps.setString(10, lbl_cantidadexistencia.getText());
            ps.setString(11, lbl_valorunitexistencia.getText());
            ps.setString(12, lbl_valortotalentrada.getText());
            ps.setString(13, txt_detalles.getText());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos registrados");

        } catch (SQLException e) {
            System.out.println("Error: " + e);

        }
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM kardex");

            // Limpiar la tabla muesrta antes de agregar nuevos datos
            DefaultTableModel model = (DefaultTableModel) tb_kardex.getModel();
            model.setRowCount(0);

            // Recorrer el resultado y agregar los datos a la tabla muesrta
            while (rs.next()) {
                int id_kardex = rs.getInt("id_kardex");
                String fecha = rs.getString("fecha");
                String detalles = rs.getString("detalles");
                String cantidad = rs.getString("cantidad");
                String valor_unitario = rs.getString("valor_unitario");
                String total_entrada = rs.getString("total_entrada");
                String cantidad_existencia = rs.getString("cantidad_existencia");
                String valorunitexis = rs.getString("valorunit_existencia");
                String valortotalexistencia = rs.getString("valortotal_existencia");

                // Agregar los datos a la tabla muesrta
                model.addRow(new Object[]{id_kardex, fecha, detalles, cantidad, valor_unitario, total_entrada, cantidad_existencia, valorunitexis, valortotalexistencia});
            }

        } catch (SQLException e) {
            System.out.println("Error al obtener los datos de la tabla: " + e);
        }


    }//GEN-LAST:event_btt_guardarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double cantidad = Double.parseDouble(txt_cantidad.getText());
        double valorUnitario = Double.parseDouble(txt_valorunitario.getText());
        double totalEntrada = cantidad * valorUnitario;
        lbl_valortotalentrada.setText(String.valueOf(totalEntrada));
        
        lbl_cantidadexistencia.setText(txt_cantidad.getText());
    lbl_valorunitexistencia.setText(txt_valorunitario.getText());
    lbl_totalexistecia.setText(lbl_valortotalentrada.getText());

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Krex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Krex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Krex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Krex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Krex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btt_guardar;
    private javax.swing.JComboBox<String> cbx_almacenamiento;
    private javax.swing.JComboBox<String> cbx_marca;
    private javax.swing.JComboBox<String> cbx_modelo;
    private javax.swing.JComboBox<String> cbx_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_cantidadexistencia;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_totalexistecia;
    private javax.swing.JLabel lbl_valortotalentrada;
    private javax.swing.JLabel lbl_valorunitexistencia;
    private javax.swing.JTable tb_kardex;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_detalles;
    private javax.swing.JTextField txt_valorunitario;
    // End of variables declaration//GEN-END:variables

    private int obtenerNuevoIdVehiculoFromDatabase() {
        int nuevoId = 0;

        try {
            Statement statement = con.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT MAX(id_kardex) FROM kardex");

            if (resultSet.next()) {
                int maxId = resultSet.getInt(1);
                nuevoId = maxId + 1;
            }
        } catch (SQLException e) {
            System.out.println("Error al obtener el nuevo ID: " + e);
        }

        return nuevoId;

    }

    private void CargarComboCategorias() {
        Connection cn = Conexionn.conectar();
        String sql = "select * from catalogo_kardex";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbx_marca.removeAllItems();
            cbx_marca.addItem("Seleccione MARCA");
            while (rs.next()) {
                cbx_marca.addItem(rs.getString("marca"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias");
        }

    }

    private void proveedor() {
        Connection cn = Conexionn.conectar();
        String sql = "select * from catalogo_kardex";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbx_proveedor.removeAllItems();
            cbx_proveedor.addItem("Seleccione PROVEEDOR");
            while (rs.next()) {
                cbx_proveedor.addItem(rs.getString("proveedor"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias");
        }

    }

   
    private void modelo() {
        Connection cn = Conexionn.conectar();
        String sql = "select * from catalogo_kardex";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbx_modelo.removeAllItems();
            cbx_modelo.addItem("Seleccione MODELO");
            while (rs.next()) {
                cbx_modelo.addItem(rs.getString("modelo"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias");
        }

    }
     private void almacenamiento() {
        Connection cn = Conexionn.conectar();
        String sql = "select * from catalogo_kardex";
        Statement st;

        try {

            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            cbx_almacenamiento.removeAllItems();
            cbx_almacenamiento.addItem("Seleccione ALMACENAMIENTO");
            while (rs.next()) {
                cbx_almacenamiento.addItem(rs.getString("almacenamiento"));
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error al cargar categorias");
        }

    }
    

}
